# Generated by Django 6.0.2 on 2026-02-13 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vagas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_gestor', models.CharField(blank=True, max_length=200)),
                ('data_solic', models.DateField(auto_now_add=True)),
                ('departamento', models.CharField(choices=[('comercial', 'Comercial'), ('fabrica', 'Fabrica'), ('financeiro', 'Financeiro'), ('rh', 'Recursos Humanos')], max_length=200)),
                ('nome_vaga', models.CharField(blank=True, help_text='Soldador, Projetista, etc.', max_length=200)),
                ('data_inicio', models.DateField()),
                ('quant_vagas', models.PositiveBigIntegerField(help_text='Digite a quantidade de vagas que gostaria de abrir, exemplo: 2')),
                ('motivo_vaga', models.TextField(help_text='Exp: Por conta de uma reposição pessoal.')),
                ('nome_sub', models.CharField(max_length=200)),
                ('sexo', models.CharField(choices=[('masculino', 'Masculino'), ('feminino', 'Feminino'), ('naoexp', 'Prefiro não especificar.')], max_length=100)),
                ('escola', models.CharField(choices=[('fundamental', 'Fundamental'), ('medio', 'Ensino Médio'), ('superior', 'Superior'), ('tecnico', 'Técnico')], max_length=100)),
                ('observacao', models.TextField(help_text="Digite aqui alguma observação que queira fazer sobre o candidato substituto, exemplo: 'O candidato tem experiência prévia na função.'")),
                ('status', models.CharField(choices=[('em_analise', 'Em Analise'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], default='em_analise', max_length=20)),
                ('ativa', models.BooleanField(default=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('observacao_rh', models.TextField(blank=True)),
                ('solicitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Candidato',
                'verbose_name_plural': 'Candidatos',
                'ordering': ['-data_cadastro'],
            },
        ),
    ]
