# Generated by Django 6.0.2 on 2026-02-13 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagasAbertas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vagas',
            old_name='departamento',
            new_name='abertura_para_o_departamento',
        ),
        migrations.RenameField(
            model_name='vagas',
            old_name='nome_sub',
            new_name='nome_do_substituido',
        ),
        migrations.RenameField(
            model_name='vagas',
            old_name='quant_vagas',
            new_name='quantidades_de_vagas',
        ),
        migrations.AlterField(
            model_name='vagas',
            name='motivo_vaga',
            field=models.CharField(choices=[('substitucao', 'Substituição'), ('nova_vaga', 'Novas Vagas')], max_length=100),
        ),
    ]
